# Generated by Django 4.0.1 on 2022-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Малоэтажное строительство', 'Малоэтажное строительство'), ('Жилой комплекс', 'Жилой комплекс'), ('Коммерческая недвижимость', 'Коммерческая недвижимость'), ('Ж/Б конструкции', 'Ж/Б конструкции'), ('Навесные вентилируемые фасады', 'Навесные вентилируемые фасады'), ('Другое', 'Другое')], default='', max_length=300),
        ),
    ]
